// ─── Packing Lists Data ───────────────// 
// Edit this file to update your lists.
// Each list has: id, label, icon, and items[].
// Each item has: name and qty.

const packingData = [
  {
    id: "mushu",
    label: "Mushu",
    icon: "🐾",
    items: [
      { name: "Quilt to protect bed",  qty: "1" },
      { name: "Towels",                qty: "3" },
      { name: "Dog food",              qty: "1" },
      { name: "Dog Treats",            qty: "1" },
      { name: "Long Leash",            qty: "1" },
      { name: "Short Leash",           qty: "1" },
      { name: "Calming Spray",         qty: "1" },
      { name: "Food Bowl",             qty: "1" },
      { name: "Water Bowl",            qty: "1" },
      { name: "Toys",                  qty: "1" },
      { name: "Harness",               qty: "1" },
      { name: "Poop Bags",             qty: "1" },
      { name: "Bed",                   qty: "—" },
      { name: "Duvet and Blanket",     qty: "—" },
      { name: "Jacket",                qty: "—" },
      { name: "Zip ties",              qty: "—" },
    ]
  },
  {
    id: "olly_bath",
    label: "Olly Bath",
    icon: "🛁",
    items: [
      { name: "Bath Pillow",           qty: "1" },
      { name: "Baby Shampoo",          qty: "1" },
      { name: "Baby Soap",             qty: "1" },
      { name: "Baby Oil",              qty: "1" },
      { name: "Baby Insect Spray",     qty: "1" },
      { name: "Nappies (Caddy)",       qty: "1" },
      { name: "New Pack of Nappies",   qty: "96" },
      { name: "Wet wipes",             qty: "2" },
      { name: "Calpol",                qty: "1" },
      { name: "Gripe Water",           qty: "1" },
      { name: "Facecloth",             qty: "3" },
      { name: "Washcloth",             qty: "1" },
      { name: "Baby Towels",           qty: "2" },
      { name: "Syringe",               qty: "1" },
      { name: "Earbuds",               qty: "1 pack" },
      { name: "Cotton Wool",           qty: "1 pack" },
      { name: "Sudo cream",            qty: "1" },
      { name: "Sanitiser",             qty: "1" },
      { name: "Hair Brush",            qty: "—" },
      { name: "Pamper bag (pink)",     qty: "1" },
      { name: "Baby Cream (Body)",     qty: "1" },
      { name: "Epimax Ointment",       qty: "1" },
      { name: "Puppy Pads",            qty: "10" },
      { name: "Head scrubber",         qty: "1" },
      { name: "Nail File",             qty: "1" },
      { name: "Snot Sucker",           qty: "1" },
      { name: "Baby Bath",             qty: "1" },
    ]
  },
  {
    id: "olly_general",
    label: "Olly General",
    icon: "👶",
    items: [
      { name: "Books",                 qty: "2" },
      { name: "Thick Blanket",         qty: "3" },
      { name: "Thin Blanket",          qty: "2" },
      { name: "Weighted Duck",         qty: "1" },
      { name: "Burp Cloths",           qty: "2/day" },
      { name: "Vests",                 qty: "2/day" },
      { name: "Outfit",                qty: "2/day" },
      { name: "Fluffies",              qty: "1/day" },
      { name: "Socks",                 qty: "1/day" },
      { name: "Mittens",               qty: "1/day" },
      { name: "Beanie",                qty: "1/day" },
      { name: "Bibs",                  qty: "2/day" },
      { name: "Hats",                  qty: "1 trip" },
      { name: "Sleeping Bags",         qty: "2" },
      { name: "Baa-Berry",             qty: "1" },
      { name: "Ball Toys",             qty: "2" },
      { name: "Play Mat",              qty: "1" },
      { name: "Under Mats",            qty: "4" },
      { name: "Down Jacket",           qty: "1" },
      { name: "Chickens",              qty: "3" },
      { name: "Angel Care Monitor",    qty: "1" },
      { name: "Wireless Monitor",      qty: "1" },
      { name: "Bassinette",            qty: "1" },
      { name: "Pram",                  qty: "1" },
      { name: "Heater",                qty: "1" },
    ]
  },
  {
    id: "olly_kitchen",
    label: "Olly Kitchen",
    icon: "🍼",
    items: [
      { name: "Drying Racks",          qty: "2" },
      { name: "Bottles",               qty: "9" },
      { name: "Cleaning Buckets",      qty: "2" },
      { name: "Bottle Brushes",        qty: "3" },
      { name: "Avent Milk Containers", qty: "6" },
      { name: "Roller Towel",          qty: "2" },
      { name: "Bottle Warmer",         qty: "1" },
      { name: "Steriliser",            qty: "1" },
      { name: "Dummies",               qty: "6" },
      { name: "Dummy Clips",           qty: "2" },
      { name: "Dishwashing Liquid",    qty: "1" },
      { name: "Milton's",              qty: "1" },
      { name: "Cloths",                qty: "1/day" },
      { name: "Dishcloths",            qty: "1/day" },
      { name: "2 x Pumps",             qty: "2" },
      { name: "Pump Parts",            qty: "all" },
      { name: "Spare Pump Parts",      qty: "all" },
      { name: "Pump Charger",          qty: "1" },
      { name: "Cell phone Charger",    qty: "1" },
      { name: "Sanitiser",             qty: "1" },
      { name: "Hand Wash",             qty: "1" },
      { name: "Gloves",                qty: "1" },
    ]
  },
  {
    id: "extras",
    label: "Extras",
    icon: "🎒",
    items: [
      { name: "Charcoal",              qty: "per braai" },
      { name: "Firelighters",          qty: "per braai" },
      { name: "Braai Grid",            qty: "—" },
      { name: "Matches",               qty: "—" },
      { name: "Candles",               qty: "—" },
      { name: "Kittens",               qty: "—" },
      { name: "30 Seconds",            qty: "—" },
      { name: "Banana Grams",          qty: "—" },
      { name: "Swing ball",            qty: "—" },
      { name: "Picnic Blanket",        qty: "—" },
      { name: "Black Bags",            qty: "—" },
      { name: "Batteries",             qty: "—" },
      { name: "Skottle",               qty: "—" },
      { name: "Gas Bottle",            qty: "—" },
      { name: "Heater",                qty: "—" },
      { name: "Kettle",                qty: "—" },
      { name: "Wood",                  qty: "—" },
      { name: "Salt and Pepper",       qty: "—" },
      { name: "Oil",                   qty: "—" },
      { name: "Tea",                   qty: "—" },
      { name: "Hot Chocolate",         qty: "—" },
      { name: "Milo",                  qty: "—" },
      { name: "Milk",                  qty: "—" },
      { name: "Kokee",                 qty: "—" },
      { name: "Slimsy",                qty: "—" },
      { name: "Beers",                 qty: "—" },
      { name: "Wine",                  qty: "—" },
      { name: "Vitamins",              qty: "—" },
      { name: "Roostekoek Stuff",      qty: "—" },
    ]
  }
];
